export const FETCH_POST_REQUEST = 'FETCH_POST_REQUEST';
export const FETCH_POST_SUCCESS = 'FETCH_POST_SUCCESS';
export const FETCH_POST_FAILED = 'FETCH_POST_FAILED';

export const SORT_POSTS_ASC = 'SORT_POSTS_ASC';
export const SORT_POSTS_DESC = 'SORT_POSTS_DESC';

export const SEARCH_POSTS = 'SEARCH_POSTS';
